// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20210206150903_SeedDataTitle")]
    partial class SeedDataTitle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value-1",
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Value-2",
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value-3",
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Value-4",
                            Title = "Title 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
